---
version: 2.1
jobs:
  build:
    working_directory: ~/ansible-role-python
    docker:
      - image: cimg/python:3.12.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Install
          command: pipenv install --dev
      - setup_remote_docker
      - run:
          name: Molecule
          command: |
            while sleep 60; do echo "Still running..."; done &
            pipenv run molecule test
            kill %1
