---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: rockylinux
    image: geerlingguy/docker-rockylinux9-ansible:latest
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: yes
    pre_build_image: yes
    env:
      python_version: "${python_version:-3.12.4}"
provisioner:
  name: ansible
verifier:
  name: ansible
